version: '3.8'
networks:
  minesweeper_app:
    driver: bridge

services:
  web:
    build: .
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - minesweeper_app

  redis:
    image: redis:latest
    restart: always
    command: redis-server --port 6379
    ports:
      - '6378:6379'
    volumes:
      - redisdata-redis:/data
    networks:
      - minesweeper_app

volumes:
  pgdata-db:
  redisdata-redis:
